const LAT=43.2965,LON=5.3698;
const weatherUrl=`https://api.open-meteo.com/v1/forecast?latitude=${LAT}&longitude=${LON}&current=temperature_2m,relative_humidity_2m,apparent_temperature,wind_speed_10m,weather_code&hourly=precipitation_probability,wind_gusts_10m,weather_code&forecast_days=2&timezone=Europe%2FParis`;
const eventsUrl='https://france-evasion-regions.com/api/open/evenements.json?ville=Marseille&departement=13';
const $=id=>document.getElementById(id);
const codeText={0:['☀️','Ciel dégagé'],1:['🌤️','Peu nuageux'],2:['⛅','Partiellement nuageux'],3:['☁️','Couvert'],45:['🌫️','Brouillard'],48:['🌫️','Brouillard givrant'],51:['🌦️','Bruine'],53:['🌦️','Bruine'],55:['🌧️','Bruine forte'],61:['🌧️','Pluie faible'],63:['🌧️','Pluie'],65:['🌧️','Forte pluie'],71:['🌨️','Neige'],73:['🌨️','Neige'],75:['❄️','Forte neige'],80:['🌦️','Averses'],81:['🌦️','Averses'],82:['⛈️','Fortes averses'],95:['⛈️','Orage'],96:['⛈️','Orage avec grêle'],99:['⛈️','Orage avec grêle']};
async function loadWeather(){try{const r=await fetch(weatherUrl);const j=await r.json();const c=j.current;const [icon,text]=codeText[c.weather_code]||['🌤️','Météo'];$('temp').textContent=Math.round(c.temperature_2m)+'°';$('feels').textContent=Math.round(c.apparent_temperature)+'°';$('wind').textContent=Math.round(c.wind_speed_10m)+' km/h';$('humidity').textContent=c.relative_humidity_2m+'%';$('weatherText').textContent=text;$('weatherIcon').textContent=icon;renderWeatherAlerts(j)}catch(e){$('weatherText').textContent='Météo indisponible';}}
function renderWeatherAlerts(j){const h=j.hourly;let cards=[];const maxGust=Math.max(...h.wind_gusts_10m.slice(0,24));const maxRain=Math.max(...h.precipitation_probability.slice(0,24));if(maxGust>=70)cards.push(['urgent','💨 Vent fort','Rafales prévues jusqu’à '+Math.round(maxGust)+' km/h dans les prochaines 24 h.']);if(maxRain>=70)cards.push(['info','🌧️ Pluie probable','Probabilité maximale de précipitations : '+Math.round(maxRain)+' % dans les prochaines 24 h.']);if(!cards.length)cards.push(['','🟢 Aucun signal météo majeur','Aucun seuil simple d’alerte détecté dans les prochaines 24 h.']);$('alerts').innerHTML=cards.map(x=>`<div class="card ${x[0]}"><span class="tag">MÉTÉO</span><h3>${x[1]}</h3><p>${x[2]}</p></div>`).join('')}
function normalizeEvents(j){const arr=Array.isArray(j)?j:(j.events||j.data||j.results||[]);return arr.map(e=>({title:e.title?.fr||e.title||e.name||'Événement',date:e.date||e.startDate||e.start||e.timing?.begin||'',place:e.location?.name||e.location?.city||e.city||'Marseille',url:e.url||e.link||''})).filter(e=>/marseille/i.test((e.place||'')+' '+(e.title||''))).slice(0,20)}
async function loadEvents(){try{const r=await fetch(eventsUrl);if(!r.ok)throw Error();const data=normalizeEvents(await r.json());if(!data.length)throw Error();$('eventCount').textContent=data.length+' à venir';$('events').innerHTML=data.map(e=>`<article class="card"><span class="tag">ÉVÉNEMENT</span><h3>${esc(e.title)}</h3><p>📍 ${esc(e.place)}${e.date?' · 📅 '+esc(e.date):''}</p>${e.url?`<p><a href="${e.url}" target="_blank" rel="noopener">Voir la source →</a></p>`:''}</article>`).join('')}catch(e){$('eventCount').textContent='Source indisponible';$('events').innerHTML='<div class="card"><span class="tag">INFO</span><h3>Événements non chargés</h3><p>La source événementielle publique n’a pas répondu. La météo reste disponible. Nous ajouterons d’autres sources dans la version serveur.</p></div>'}}
function esc(s){return String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
async function notifications(){if(!('Notification'in window)){alert('Les notifications ne sont pas prises en charge ici.');return}const p=await Notification.requestPermission();if(p==='granted')new Notification('Marseille Alert',{body:'Les alertes sont activées sur cet appareil.'})}
$('refresh').onclick=()=>{loadWeather();loadEvents()};$('notifyBtn').onclick=notifications;loadWeather();loadEvents();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
